version: '3.8'

services:
  # AI Cloud Storage Service - Modular Monolith
  app:
    extends:
      file: docker-compose.base.yml
      service: app
    build:
      target: production
    container_name: aicloud-app
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DATABASE_URL=postgresql+asyncpg://aicloud:aicloud@postgres:5432/aicloud
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
      - MINIO_SECURE=false
      - JWT_SECRET_KEY=${JWT_SECRET_KEY:-your-secret-key-here}
      - JWT_ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      # Module-specific configurations
      - AUTH_MODULE_ENABLED=true
      - STORAGE_MODULE_ENABLED=true
      - AI_PROCESSOR_MODULE_ENABLED=true
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    networks:
      - aicloud-net
    deploy:
      replicas: ${APP_REPLICAS:-2}
      resources:
        limits:
          cpus: '2'
          memory: 4G
      restart_policy:
        condition: on-failure
        max_attempts: 3

  # Database
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    container_name: aicloud-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aicloud
      POSTGRES_PASSWORD: aicloud
      POSTGRES_DB: aicloud
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aicloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aicloud-net

  # Redis Cache
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    container_name: aicloud-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aicloud-net

  # MinIO Object Storage
  minio:
    extends:
      file: docker-compose.base.yml
      service: minio
    container_name: aicloud-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - aicloud-net

networks:
  aicloud-net:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  minio_data: