version: '3.8'

services:
  # Storage
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --console-address ":9001" /data
    volumes:
      - minio_data:/data

  # Vector Database
  weaviate:
    image: semitechnologies/weaviate:1.21.2
    ports:
      - "8080:8080"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: text2vec-transformers
      ENABLE_MODULES: text2vec-transformers
      TRANSFORMERS_INFERENCE_API: http://t2v-transformer:8080
    depends_on:
      - t2v-transformer

  t2v-transformer:
    image: semitechnologies/transformers-inference:sentence-transformers-multi-qa-MiniLM-L6-cos-v1
    environment:
      ENABLE_CUDA: 0

  # Message Broker
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  # Database
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: aicloud
      POSTGRES_PASSWORD: aicloud
      POSTGRES_DB: aicloud
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Services
  storage-service:
    build: ./services/storage
    ports:
      - "8000:8000"
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    depends_on:
      - minio

  ai-processor:
    build: ./services/ai-processor
    ports:
      - "8001:8001"
    environment:
      MINIO_HOST: minio
      MINIO_PORT: 9000
      MINIO_USE_SSL: "false"
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      WEAVIATE_URL: http://weaviate:8080
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
      EMBEDDING_MODEL: sentence-transformers/all-MiniLM-L6-v2
    volumes:
      - ./services/ai-processor:/app
    depends_on:
      - minio
      - kafka
      - weaviate
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

volumes:
  minio_data:
  postgres_data: