services:
  # Database - Development
  postgres:
    extends:
      file: docker-compose.base.yml
      service: postgres
    container_name: aicloud-postgres-dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: aicloud
      POSTGRES_PASSWORD: aicloud
      POSTGRES_DB: aicloud
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U aicloud"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - aicloud-net

  # Redis Cache - Development
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    container_name: aicloud-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes --requirepass ""
    networks:
      - aicloud-net

  # MinIO Object Storage - Development
  minio:
    extends:
      file: docker-compose.base.yml
      service: minio
    container_name: aicloud-minio-dev
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data_dev:/data
    command: server /data --console-address ":9001"
    networks:
      - aicloud-net

volumes:
  postgres_data_dev:
  redis_data_dev:
  minio_data_dev:

networks:
  aicloud-net:
    driver: bridge
