"""Fix dependencies in database schema

Revision ID: 20241126_fix_dependencies
Revises: e4117c04da4d
Create Date: 2024-11-26 03:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '20241126_fix_dependencies'
down_revision = 'e4117c04da4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Drop foreign key constraints first
    op.execute('ALTER TABLE folder_files DROP CONSTRAINT IF EXISTS folder_files_file_id_fkey')
    op.execute('ALTER TABLE file_versions DROP CONSTRAINT IF EXISTS file_versions_file_id_fkey')
    op.execute('ALTER TABLE shared_items DROP CONSTRAINT IF EXISTS shared_items_file_id_fkey')
    op.execute('ALTER TABLE file_tags DROP CONSTRAINT IF EXISTS file_tags_file_id_fkey')
    op.execute('ALTER TABLE file_metadata DROP CONSTRAINT IF EXISTS file_metadata_file_id_fkey')
    op.execute('ALTER TABLE processing_tasks DROP CONSTRAINT IF EXISTS processing_tasks_file_id_fkey')
    
    # Now we can safely drop the tables
    op.drop_table('folder_files')
    op.drop_table('file_versions')
    op.drop_table('shared_items')
    op.drop_table('file_tags')
    op.drop_table('file_metadata')
    op.drop_table('processing_tasks')
    op.drop_table('files')


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
