"""Create initial schema

Revision ID: 6d25e058d779
Revises: 20241126_fix_dependencies
Create Date: 2024-11-26 20:32:59.997120+00:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d25e058d779'
down_revision = '20241126_fix_dependencies'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
